### ISSUE TITLE
time for prediction

### ISSUE THREAD

**Issue by kashyappiyush1998** [99991/testing#2]
Time Taken for foreground prediction is very high, compared to FBA matting and other deep learning matting algorithm. Am I doing something wrong?

**Comment by 99991** [comment]
Are you sure that foreground prediction is slower than alpha matting? `estimate_foreground_ml` should be much faster than `estimate_alpha_lkm` or `estimate_alpha_cf`. There also are even faster CUDA and OpenCL implementations for foreground estimation if your users have GPUs: https://pymatting.github.io/pymatting.foreground.html#pymatting-foreground-estimate-foreground-ml-cupy-module

There also is a GPU implementation for alpha matting here https://github.com/rocketman768/gpumatting but I am not sure how well it works.

FBA matting uses the GPU for everything already and does both things at once, so if it works better for some images, if you have a way to distribute the model and if you can deal with the license terms, just use that instead or provide an option to the user to select one of the methods.
